/**
  ******************************************************************************
  * @file    system_stm32l1xx.c
  * @author  MCD Application Team
  * @version V1.1.1
  * @date    13-April-2012
  * @brief   CMSIS Cortex-M3 Device Peripheral Access Layer System Source File.
  *          This file contains the system clock configuration for STM32L1xx Ultra
  *          Low Power devices, and is generated by the clock configuration
  *          tool "STM32L1xx_Clock_Configuration_V1.1.0.xls".
  *             
  * 1.  This file provides two functions and one global variable to be called from 
  *     user application:
  *      - SystemInit(): Setups the system clock (System clock source, PLL Multiplier
  *                      and Divider factors, AHB/APBx prescalers and Flash settings),
  *                      depending on the configuration made in the clock xls tool. 
  *                      This function is called at startup just after reset and 
  *                      before branch to main program. This call is made inside
  *                      the "startup_stm32l1xx_xx.s" file.
  *                        
  *      - SystemCoreClock variable: Contains the core clock (HCLK), it can be used
  *                                  by the user application to setup the SysTick 
  *                                  timer or configure other parameters.
  *                                     
  *      - SystemCoreClockUpdate(): Updates the variable SystemCoreClock and must
  *                                 be called whenever the core clock is changed
  *                                 during program execution.   
  *      
  * 2. After each device reset the MSI (2.1 MHz Range) is used as system clock source.
  *    Then SystemInit() function is called, in "startup_stm32l1xx_xx.s" file, to
  *    configure the system clock before to branch to main program.    
  *    
  * 3. If the system clock source selected by user fails to startup, the SystemInit()
  *    function will do nothing and MSI still used as system clock source. User can 
  *    add some code to deal with this issue inside the SetSysClock() function.
  * 
  * 4. The default value of HSE crystal is set to 8MHz, refer to "HSE_VALUE" define
  *    in "stm32l1xx.h" file. When HSE is used as system clock source, directly or
  *    through PLL, and you are using different crystal you have to adapt the HSE
  *    value to your own configuration.
  * 
  * 5. This file configures the system clock as follows:  
  *=============================================================================
  *                         System Clock Configuration
  *=============================================================================
  *        System Clock source          | PLL(HSE)
  *-----------------------------------------------------------------------------
  *        SYSCLK                       | 32000000 Hz
  *-----------------------------------------------------------------------------
  *        HCLK                         | 32000000 Hz
  *-----------------------------------------------------------------------------
  *        AHB Prescaler                | 1
  *-----------------------------------------------------------------------------
  *        APB1 Prescaler               | 1
  *-----------------------------------------------------------------------------
  *        APB2 Prescaler               | 1
  *-----------------------------------------------------------------------------
  *        HSE Frequency                | 8000000 Hz
  *-----------------------------------------------------------------------------
  *        PLL DIV                      | 3
  *-----------------------------------------------------------------------------
  *        PLL MUL                      | 12
  *-----------------------------------------------------------------------------
  *        VDD                          | 3.3 V
  *-----------------------------------------------------------------------------
  *        Vcore                        | 1.8 V (Range 1)
  *-----------------------------------------------------------------------------
  *        Flash Latency                | 1 WS
  *-----------------------------------------------------------------------------
  *        SDIO clock (SDIOCLK)         | 48000000 Hz
  *-----------------------------------------------------------------------------
  *        Require 48MHz for USB clock  | Disabled
  *-----------------------------------------------------------------------------
  *=============================================================================
  ******************************************************************************
  * @attention
  *
  * <h2><center>&copy; COPYRIGHT 2012 STMicroelectronics</center></h2>
  *
  * Licensed under MCD-ST Liberty SW License Agreement V2, (the "License");
  * You may not use this file except in compliance with the License.
  * You may obtain a copy of the License at:
  *
  *        http://www.st.com/software_license_agreement_liberty_v2
  *
  * Unless required by applicable law or agreed to in writing, software 
  * distributed under the License is distributed on an "AS IS" BASIS, 
  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  * See the License for the specific language governing permissions and
  * limitations under the License.
  *
  ******************************************************************************
  */

#include "stm32l1xx.h"

/** Uncomment the following line if you need to relocate the vector table to SRAM. */
/* #define VECT_TAB_SRAM */
/** Vector table offset, must be multiple of 0x200 */
#define VECT_TAB_OFFSET 0x00

static void SetSysClock(void);

void SystemInit(void) {
	/* Set MSION bit */
	RCC->CR |= 0x00000100;

	/* Reset SW[1:0], HPRE[3:0], PPRE1[2:0], PPRE2[2:0], MCOSEL[2:0] and MCOPRE[2:0] bits */
	RCC->CFGR &= 0x88FFC00C;

	/* Reset HSION, HSEBYP, HSEON, CSSON and PLLON bits */
	RCC->CR &= 0xEEFAFFFE;

	/* Reset PLLSRC, PLLMUL[3:0] and PLLDIV[1:0] bits */
	RCC->CFGR &= 0xFF02FFFF;

	/* Disable all interrupts */
	RCC->CIR = 0x00000000;

	/* Configure the System clock frequency, AHB/APBx prescalers and Flash settings */
	SetSysClock();

#ifdef VECT_TAB_SRAM
	SCB->VTOR = SRAM_BASE | VECT_TAB_OFFSET;
#else
	SCB->VTOR = FLASH_BASE | VECT_TAB_OFFSET;
#endif
}

/**
 * @brief  Configures the System clock frequency, AHB/APBx prescalers and Flash 
 *         settings.
 * @note   This function should be called only once the RCC clock configuration  
 *         is reset to the default reset state (done in SystemInit() function).
 * @param  None
 * @retval None
 */
static void SetSysClock(void) {
	uint32_t startUpCounter = HSE_STARTUP_TIMEOUT;
	// Enable HSE and LSI
	RCC->CR |= RCC_CR_HSEON;
	RCC->CSR |= RCC_CSR_LSION;
	// HCLK = SYSCLK / 1, PCLK2 = HCLK / 1, PCLK1 = HCLK / 1
	RCC->CFGR = (RCC->CFGR & ~(RCC_CFGR_HPRE | RCC_CFGR_PPRE2 | RCC_CFGR_PPRE1)) |
		RCC_CFGR_HPRE_DIV1 | RCC_CFGR_PPRE2_DIV1 | RCC_CFGR_PPRE1_DIV1;
	// Wait till HSE is ready
	while (!(RCC->CR & RCC_CR_HSERDY) && --startUpCounter > 0);
	if (startUpCounter > 0) {
		// Enable 64-bit access, prefetch buffer, 1 WS
		// NOTE These cannot be combined into one statement!
		FLASH->ACR |= FLASH_ACR_ACC64;
		FLASH->ACR |= FLASH_ACR_PRFTEN | FLASH_ACR_LATENCY;
		// Enable clock to PWR module
		RCC->APB1ENR |= RCC_APB1ENR_PWREN;
		__DSB();
		// Select Voltage Range 1 (1.8 V) required for USB
		PWR->CR = PWR_CR_VOS_0;
		__DSB();
		// Wait until the voltage regulator is ready
		while (PWR->CSR & PWR_CSR_VOSF);
		// PLL configuration: *12, /3 (overall X4)
		RCC->CFGR = (RCC->CFGR & ~(RCC_CFGR_PLLSRC | RCC_CFGR_PLLMUL | RCC_CFGR_PLLDIV)) |
			RCC_CFGR_PLLSRC_HSE | RCC_CFGR_PLLMUL12 | RCC_CFGR_PLLDIV3;
		// Enable PLL
		RCC->CR |= RCC_CR_PLLON;
		// Wait till PLL is ready
		while (!(RCC->CR & RCC_CR_PLLRDY) && --startUpCounter > 0);
		if (startUpCounter > 0) {
			// Select PLL as system clock source
			RCC->CFGR = (RCC->CFGR & ~RCC_CFGR_SW) | RCC_CFGR_SW_PLL;
			// Wait till PLL is used as system clock source
			while ((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_PLL && --startUpCounter > 0);
		}
	}
	if (startUpCounter == 0) {
		// The MSI will be selected as system clock (this allows us to come up, but w/o USB)
		RCC->CFGR = (RCC->CFGR & ~RCC_CFGR_SW) | RCC_CFGR_SW_MSI;
		while ((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_MSI);
		// If HSE fails to start-up, or if PLL fails to lock
		RCC->CR &= ~(RCC_CR_HSEON | RCC_CR_PLLON);
	}
	// Wait for LSI to be ready
	while (!(RCC->CSR & RCC_CSR_LSIRDY));
	// Set the MSI to 1.048 MHz
	RCC->ICSCR = (RCC->ICSCR & ~RCC_ICSCR_MSIRANGE) | RCC_ICSCR_MSIRANGE_4;
	__DSB();
}

/************************ (C) COPYRIGHT STMicroelectronics *****END OF FILE****/
